apiVersion: v1
kind: Service
metadata:
  name: user_service-service
spec:
  selector:
    app: user_service
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
  type: NodePort