apiVersion: apps/v1
kind: Deployment
metadata:
  name: user_service
  labels:
    app: user_service
spec:
  replicas: 2
  selector:
    matchLabels:
      app: user_service
  template:
    metadata:
      name: user_service
      labels:
        app: user_service
    spec:
      containers:
        - name: user_service
          image: user_service:latest
          imagePullPolicy: Never
          ports:
            - containerPort: 8080
              protocol: TCP
      restartPolicy: Always
